version: "2.32.4"

services:
  social-platform-app-dev:
    build:
      context: .
      target: dev
    container_name: "social-platform-app-dev"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  social-platform-app-prod:
    build:
      context: .
      target: prod
    container_name: "social-platform-app-prod"
    ports:
      - "8001:8000"
    env_file:
      - ./.env
